---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-common-static
  - clickhouse-server
vector_version: "0.29.1"

vector_config: | 
 [sources.dummy_logs]
 type = "demo_logs"
 format = "syslog"
 interval = 1

 [transforms.parse_logs]
 type = "remap"
 inputs = ["dummy_logs"]
 source = '''
 . = parse_syslog!(string!(.message))
 '''

 [sinks.print]
 type = "console"
 inputs = ["parse_logs"]
 encoding.codec = "json"